from tqdm import tqdm
from elasticsearch import Elasticsearch
import time
import os



data_folder = './datasets/collectionandqueries'
# Read the corpus files, that contain all the passages. Store them in the corpus dict
# corpus = {}
# collection_filepath = os.path.join(data_folder, 'collection.tsv')

# with open(collection_filepath, 'r', encoding='utf8') as fIn:
#     for line in fIn:
#         pid, passage = line.strip().split("\t")
#         corpus[pid] = passage


# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "LdGYpuBImRmNXLYlTgNPsCvS"

# Found in the 'Manage Deployment' page
CLOUD_ID = "Information_Retrivial_Project:ZXVyb3BlLXdlc3QzLmdjcC5jbG91ZC5lcy5pbzo0NDMkODFlMGE0NjdkZmRhNDlhY2EzNTUzN2JiNjI1YjA3NjUkZmY1N2FiOWQ0MzljNDYzM2E2Yzk4ZTNiNDI3OTgxYTQ="

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

# Successful response!
print(client.info())


# For each query-document pair
# for query in ['bonjour, je suis charles']:
#     # Calculate BM25 score
#     print('running es query')
#     res = bm25.retriever.es.lexical_search(text=query, top_hits=100) 
#     print('end es query')
#     # The BM25 score is in the '_score' field of the response
#     print(res['hits']['hits'])
#     for hit in res['hits']['hits']:
#         bm25_score = hit['_score']
#         document_id = hit['_id']
#         print(bm25_score)
#         print(document_id)
#         break
        